apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: hackatron
  name: hackatron
spec:
  replicas: 1
  selector:
    app: hackatron
  template:
    metadata:
      labels:
        app: hackatron
    spec:
      containers:
      - env:
        - name: MONGO_URL
          value: mongodb://mongo:27017/hackatron
        - name: MONGO_OPLOG_URL
          value: mongodb://mongo:27017/local?authSource=hackatron
        - name: ROOT_URL
          value: http://hackatronapp.co/
        image: paralin/hackatron:latest
        imagePullPolicy: Always
        name: hackatron
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
