apiVersion: v1
kind: Service
metadata:
  name: hackatron
  labels:
    name: hackatron
    app: hackatron
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: web
      name: web
  selector:
    app: hackatron
